# @Project:       Tier 2 Support Task Automation Portal
# @Version:       0.1
# @Author:        Oleg Snegirev <ol.snegirev@gmail.com>
# @Functionality: A basic travis.yml boilerplate for T2 Portal projects

language: python

python:
  - 2.7.13

dist: trusty
addons:
  firefox: latest

services: 
  - mysql

env:
  - DJANGO=1.8.18 DB=mysql MOZ_HEADLESS=1

before_install:
  - export DJANGO_SETTINGS_MODULE=pos_tools_portal.settings
  - export PYTHONPATH=$HOME/builds/lenchevsky/t2-portal
  - export PIP_USE_MIRRORS=true
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver*.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

install:
  - pip install -r ./tools/requirements.txt
  - pip install django==$DJANGO --quiet

before_script:
  - mysql -e 'create database travis_ci_db;'
  - python pos_tools_portal/manage.py makemigrations --noinput    # Fetch DB changes
  - python pos_tools_portal/manage.py migrate                     # Apply database migrations
  - python pos_tools_portal/manage.py collectstatic --noinput     # Collect static files
  - python pos_tools_portal/manage.py check

script:
  - python pos_tools_portal/manage.py test pos_tasks  --liveserver=localhost:8000