# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='task',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='value',
        ),
        migrations.AddField(
            model_name='parameter',
            name='default_value',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='task',
            name='parameters',
            field=models.ManyToManyField(to='pos_tasks.Parameter'),
        ),
    ]
