# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_tasks', '0002_auto_20171108_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=240)),
                ('executable', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='rest_headers',
            field=models.ManyToManyField(to='pos_tasks.Header'),
        ),
    ]
