# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_tasks', '0003_auto_20171108_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='reference_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='task',
            name='rest_url',
            field=models.URLField(max_length=255),
        ),
    ]
