# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_tasks', '0004_auto_20171108_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='header',
            old_name='reference_name',
            new_name='name',
        ),
    ]
