# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_tasks', '0005_auto_20171108_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_successful', models.BooleanField()),
                ('output', models.CharField(max_length=500)),
                ('task', models.ManyToManyField(to='pos_tasks.Task')),
            ],
        ),
    ]
