# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_tasks', '0006_executionresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('jenkins_url', models.URLField(max_length=250)),
                ('jenkins_user', models.CharField(max_length=50)),
                ('jenkins_token', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Environment',
        ),
        migrations.AddField(
            model_name='task',
            name='jenkins_job_name',
            field=models.CharField(default='POS', max_length=240),
        ),
    ]
