# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 05:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos_tasks', '0007_auto_20171109_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pos_tasks.Project'),
        ),
    ]
