# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_tasks', '0009_auto_20171109_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionresult',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
