# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_tasks', '0010_executionresult_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executionresult',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='results',
            field=models.ManyToManyField(to='pos_tasks.ExecutionResult'),
        ),
    ]
