# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_tasks', '0012_auto_20171110_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionresult',
            name='user_signature',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
