# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_tasks', '0013_executionresult_user_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionresult',
            name='jenkins_build_number',
            field=models.CharField(default='1', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='executionresult',
            name='jenkins_job_name',
            field=models.CharField(default='POS', max_length=240, null=True),
        ),
    ]
