# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_tasks', '0014_auto_20171110_0136'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('active', models.BooleanField()),
                ('parameters', models.ManyToManyField(to='pos_tasks.Parameter')),
            ],
        ),
    ]
