# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos_tasks', '0015_simpletask'),
    ]

    operations = [
        migrations.CreateModel(
            name='RESTTask',
            fields=[
                ('simpletask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pos_tasks.SimpleTask')),
                ('rest_url', models.URLField(max_length=255)),
                ('rest_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], default='GET', max_length=6)),
                ('rest_headers', models.ManyToManyField(to='pos_tasks.Header')),
            ],
            bases=('pos_tasks.simpletask',),
        ),
    ]
