# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_tasks', '0016_resttask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='rest_headers',
        ),
        migrations.RemoveField(
            model_name='task',
            name='rest_method',
        ),
        migrations.RemoveField(
            model_name='task',
            name='rest_url',
        ),
    ]
