# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 22:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos_tasks', '0018_auto_20171110_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.AddField(
            model_name='simpletask',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pos_tasks.Project'),
            preserve_default=False,
        ),
    ]
