# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-11 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_tasks', '0019_auto_20171110_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='param_type',
            field=models.CharField(choices=[('DEFAULT', 'Default Parameter'), ('URL', 'URL Parameter'), ('HEADER', 'Header Parameter')], default='DEFAULT', max_length=6),
        ),
    ]
