# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_tasks', '0020_parameter_param_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='resttask',
            name='rest_json_template',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
