# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_tasks', '0021_resttask_rest_json_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resttask',
            name='rest_url',
            field=models.CharField(max_length=255),
        ),
    ]
